# Generated by Django 2.2.2 on 2019-06-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userchangebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='balance'),
        ),
    ]
