# Generated by Django 2.2.2 on 2019-06-21 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190621_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchangebalance',
            name='user',
        ),
        migrations.AddField(
            model_name='userchangebalance',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchangebalance',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchangebalance',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Replenish'), (2, 'Withdrawal'), (3, 'Transaction')], default=1),
        ),
    ]
