# Generated by Django 2.2.2 on 2019-06-21 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190621_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchangebalance',
            name='from_user',
        ),
        migrations.AddField(
            model_name='userchangebalance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='balance_changes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
