# Generated by Django 2.2.2 on 2019-06-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190624_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to_user',
        ),
    ]
