# Generated by Django 2.2.2 on 2019-07-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190712_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reason',
            new_name='action',
        ),
    ]
