version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: 'freelance'
      MYSQL_USER: 'kel'
      MYSQL_PASSWORD: '953741'
      MYSQL_ROOT_PASSWORD: 'Djakyl98'
    restart: always
    ports:
      - "3302:3306"
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db