version: '3'

services:
  db:
    image: mysql:5.7

    environment:
      MYSQL_DATABASE: freelance
      MYSQL_USER: kel
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    restart: always
    expose:
      - "3306"
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
