# Generated by Django 2.2.2 on 2019-06-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='accepted',
            new_name='accept',
        ),
    ]
